export const cartConstants = {
    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
    RESET_CART: 'RESET_CART',
    REMOVE_CART_ITEM_REQUEST: 'REMOVE_CART_ITEM_REQUEST',
    REMOVE_CART_ITEM_SUCCESS: 'REMOVE_CART_ITEM_SUCCESS',
    REMOVE_CART_ITEM_FAILURE: 'REMOVE_CART_ITEM_FAILURE'
}