export const sellerConstants = {
    SELLER_LOGIN_REQUEST: 'SELLER_LOGIN_REQUEST',
    SELLER_LOGIN_SUCCESS: 'SELLER_LOGIN_SUCCESS',
    SELLER_LOGIN_FAILURE: 'SELLER_LOGIN_FAILURE',

    SELLER_REGISTER_REQUEST: 'SELLER_REGISTER_REQUEST',
    SELLER_REGISTER_SUCCESS: 'SELLER_REGISTER_SUCCESS',
    SELLER_REGISTER_FAILURE: 'SELLER_REGISTER_FAILURE',

    SELLER_LOGOUT_SUCCESS: 'SELLER_LOGOUT_SUCCESS',
    SELLER_LOGOUT_FAILURE: 'SELLER_LOGOUT_FAILURE',

    CLEAR_ERRORS: 'CLEAR_ERRORS'
}