export const sellerConstants = {
    SELLER_LOGIN_REQUEST: 'SELLER_LOGIN_REQUEST',
    SELLER_LOGIN_SUCCESS: 'SELLER_LOGIN_SUCCESS',
    SELLER_LOGIN_FAILURE: 'SELLER_LOGIN_FAILURE',

    SELLER_REGISTER_REQUEST: 'SELLER_REGISTER_REQUEST',
    SELLER_REGISTER_SUCCESS: 'SELLER_REGISTER_SUCCESS',
    SELLER_REGISTER_FAILURE: 'SELLER_REGISTER_FAILURE',

    SELLER_LOGOUT_SUCCESS: 'SELLER_LOGOUT_SUCCESS',
    SELLER_LOGOUT_FAILURE: 'SELLER_LOGOUT_FAILURE',

    GET_SELLER_DETAILS_REQUEST: 'GET_SELLER_DETAILS_REQUEST',
    GET_SELLER_DETAILS_SUCCESS: 'GET_SELLER_DETAILS_SUCCESS',
    GET_SELLER_DETAILS_FAILURE: 'GET_SELLER_DETAILS_FAILURE',

    ADD_FOLLOWER_REQUEST: 'ADD_FOLLOWER_REQUEST',
    ADD_FOLLOWER_SUCCESS: 'ADD_FOLLOWER_SUCCESS',
    ADD_FOLLOWER_FAILURE: 'ADD_FOLLOWER_FAILURE',

    GET_FOLLOWING_PRODUCTS: 'GET_FOLLOWING_PRODUCTS',

    CLEAR_ERRORS: 'CLEAR_ERRORS'
}